// config.js
module.exports = {
    YOUTUBE_API_KEY: '',   // Add your own API here directly or configure a .env fule
    CHANNEL_IDS: [
        'UCpa54N4vmqqUKkGJcSV62Lw',  // 20thCenturyStudios
        'UC9YHyj7QSkkSg2pjQ7M8Khg',  // paramountmovies
        'UCq0OueAsdxH6b8nyAspwViw',  // UniversalPictures
        'UCQLBOKpgXrSj3nPU-YC3K9Q',  // universalpicturesuk
        'UCz97F7dMxBNOfGYu3rx8aCw',  // sonypictures
        'UCJJap_3RGZ2UxqLTLz0K39g',  // SonyPicsUK
        'UCnLuLSV-Oi0ctqjxGgxFlmg',  // SonyAnimation
        'UCruD_lL-5fmllpKMSL-yCyQ',  // SonyPicturesClassics
        'UCuaFvcY4MhZY3U43mMt1dYQ',  // DisneyMovieTrailers
        'UC_976xMxPgzIa290Hqtk-9g',  // disneyanimation
        'UCjmJDM5pRKbUlVIzDYYWb6g',  // WarnerBrosPictures
        'UCAkuFASaTroS3_TubDrZGVA',  // dcofficial
        'UCvC4D8onUfXzvjTOM-dBfEA',  // marvel
        'UCVTQuK2CaWaTgSsoNkn5AiQ',  // HBO
        'UCgjZhV055WHIYwrmIrvtFQg',  // LionsgateMovies
        'UCU4SM3j_9TNWaSu8KdGV50g',  // FocusFeatures
        'UCFPRJAk5PTylG45BpLI5Xqw',  // miramax
        'UCVfDD0rCfni11W5Dh6qh1gg',  // Blumhouse
        'UC9ROVcERe1GyOWMUr83_MvA',  // VoltagePictures
        'UCvE8nyjdQG0_rgx9u3oqadw',  // wellgousa
        'UCravBlrXZFH19MJYdtHijSA',  // samuelgoldwynfilmcom
        'UC_bZBp05ksCrXtrQADtkN7w',  // Roadshow
        'UCK_Iaa7WoHFf-6ihn-d3e_w',  // ShoutStudios
        'UCbSLyYJPI_GlOBlDrUmnesQ',  // SignatureUK
        'UCafnP6JPjVq8AahYaThUelg',  // BleeckerStFilms
        'UCivoBJ4QdYCdnqBtso6H0NA',  // KetchupEnt
        'UC2dIDJBf9W88PxGm-uHZPaQ',  // FXNetworks
        'UCH45phx_o8pNt9PwbjxWhcA',  // RoadsideFlix
        'UCneoi6WTgRjMh4otvpwzv8w',  // magnoliapictures
        'UCCj956IF62FbT7Gouszaj9w',  // BBC
        'UCV-FSK1z6RkPjmEOfkrxYLg',  // shudder
        'UCb6-VM5UQ4Czj_d3m9EPGfg',  // mubi
        'UCXXpsFkjIbYnvw5rLfSW0XA',  // legendary
        'UCyCCbCfg3jFXD9ePNhcHKBg',  // oscopelabs
        'UClt5Bst8Ji05dZvTUdnO85g',  // openroadfilms
        'UCwEzY5IV8FzFgtNTXb2aaTA',  // ParamountGermany
        'UCPqZp43m3Cg69JkvCvXh8Eg',  // UniversalPicturesDE
        'UCn-z5y-cFNPoPWDwTBMDLlQ',  // SonyPicturesGermany
        'UCtcR5-VbtHEMqeua5Fn4idQ',  // MarvelDE
        'UCZqgRlLcvO3Fnx_npQJygcQ',  // Netflixdach
        'UC51KZjUZokzJfb08mzAGS2A',  // constantinfilm
        'UCAXpioV0Tyt8xSYYYN_9L0A',  // WildBunchGermany
        'UCd39Lj0DRDLkfImMJhDJg1A',  // visionen1997
        'UCz2Wf5Y8oPzMNUd9Mbrkn7Q',  // capelightpictures
        'UCLR6uQBWijaLqt7uCwEmRgw',  // xverleih
        'UCRA8PNbn0AACnYTpxiPpR8A',  // polyband
        'UCko2qr9j6U40qzUZe5soxnA',  // PifflMedien
        'UCy1rkKJYoowMmwTuo49P2Ow',  // arsenalfilm
        'UCC-FDEg3afqm1rzGO03OiTQ',  // farbfilmverleih
        'UCJLGEYCZBfP24caDkZe0dVQ',  // mindjazzpictures
        'UCyLPilfpZI8-XIjv7bje90Q',  // acontrafilms
        'UCt0cBVMTrblbARP1xD-oHig',  // CorazonFilms
        'UCaFEAxeTC-Y_0AFthe0Xmwg',  // DiamondFilmsLatam
        'UCgMzrSTTBfLPEtCAQAg_KmQ',  // disneyspain
        'UC6-5GpG91QdehokdUx_SeEw',  // marveles
        'UC8LEXZO4hjzVk6wO3G9pJyQ',  // MarvelLatino
        'UCOEb1Ys-soP9id323HsdrtQ',  // MorenaFilmsCine
        'UCwTKziMccZoy631_wbxk8wg',  // ParamountMexico
        'UCauapuNTraKzK1o25WwSfSQ',  // ParamountPicturesES
        'UC_3jVPUBlYajBEKGgTEEzdA',  // SonyPicturesLatam
        'UCtbGAbsn-s5xOVsFi6EykUQ',  // StarWarsLA
        'UCC3jP00sSqKASvDoOha43lg',  // UniversalPicsLatino
        'UCuON8B3q1FMIOSE-0sbC_rQ',  // universalpicturesmx
        'UChuDcrzhzSJ7BgGxdU-jQFA',  // VerticeCine
        'UCu-cVVMn41qUA-pwdEhNqhg'   // WarnerBrosPicturesLA
    ] 
};
